export const SET_LANGUAGE = 'SET_LANGUAGE'

export const SET_PAGE = 'SET_PAGE'

export const SET_CURRENT_USER ='SET_CURRENT_USER'

export const SET_LOGIN_EXCEPTION ='SET_LOGIN_EXCEPTION'

export const LOGOUT = 'LOGOUT'

export const SET_SHORT_PROFILE = 'SET_SHORT_PROFILE'

export const GET_SPORTS = 'GET_SPORTS'

export const SET_REGISTRATION_EXCEPTION = 'SET_REGISTRATION_EXCEPTION'

export const AFTER_LOGOUT = 'AFTER_LOGOUT'
